# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updateHours', models.CharField(max_length=100)),
                ('newsTitle', models.TextField(blank=True)),
                ('newsContent', models.TextField(blank=True)),
                ('newsLink', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
