# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbanews', '0005_remove_post_newsnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='newsNum',
            field=models.IntegerField(default=0),
        ),
    ]
