# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nbanews', '0006_post_newsnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='newsNum',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updateHours',
        ),
    ]
